#!/bin/sh
# Shared runtime environment helpers for Orkestrator containers.
#
# User setup scripts often install tools into per-user directories and update
# shell startup files. Native agent servers are launched later by non-interactive
# docker exec commands, so they need a persisted PATH snapshot from setup time.

ORKESTRATOR_RUNTIME_ENV_FILE="${ORKESTRATOR_RUNTIME_ENV_FILE:-/tmp/orkestrator-ai/runtime-env.sh}"

orkestrator_prepend_path() {
    if [ -z "${1:-}" ] || [ ! -d "$1" ]; then
        return 0
    fi

    case ":${PATH:-}:" in
        *":$1:"*) ;;
        *) PATH="$1${PATH:+:$PATH}" ;;
    esac
}

orkestrator_add_common_runtime_paths() {
    orkestrator_prepend_path "/usr/local/share/npm-global/bin"

    if [ -n "${BUN_INSTALL:-}" ]; then
        orkestrator_prepend_path "$BUN_INSTALL/bin"
    fi
    if [ -n "${CARGO_HOME:-}" ]; then
        orkestrator_prepend_path "$CARGO_HOME/bin"
    fi
    if [ -n "${GOPATH:-}" ]; then
        orkestrator_prepend_path "$GOPATH/bin"
    fi
    if [ -n "${PNPM_HOME:-}" ]; then
        orkestrator_prepend_path "$PNPM_HOME"
    fi
    if [ -n "${DENO_INSTALL:-}" ]; then
        orkestrator_prepend_path "$DENO_INSTALL/bin"
    fi
    if [ -n "${PYENV_ROOT:-}" ]; then
        orkestrator_prepend_path "$PYENV_ROOT/shims"
        orkestrator_prepend_path "$PYENV_ROOT/bin"
    fi
    if [ -n "${RYE_HOME:-}" ]; then
        orkestrator_prepend_path "$RYE_HOME/shims"
    fi
    if [ -n "${UV_TOOL_BIN_DIR:-}" ]; then
        orkestrator_prepend_path "$UV_TOOL_BIN_DIR"
    fi
    if [ -n "${VOLTA_HOME:-}" ]; then
        orkestrator_prepend_path "$VOLTA_HOME/bin"
    fi

    if [ -n "${HOME:-}" ]; then
        orkestrator_prepend_path "$HOME/.local/bin"
        orkestrator_prepend_path "$HOME/bin"
        orkestrator_prepend_path "$HOME/.bun/bin"
        orkestrator_prepend_path "$HOME/.cargo/bin"
        orkestrator_prepend_path "$HOME/go/bin"
        orkestrator_prepend_path "$HOME/.deno/bin"
        orkestrator_prepend_path "$HOME/.npm-global/bin"
        orkestrator_prepend_path "$HOME/.yarn/bin"
        orkestrator_prepend_path "$HOME/.config/yarn/global/node_modules/.bin"
        orkestrator_prepend_path "$HOME/.opencode/bin"
        orkestrator_prepend_path "$HOME/.claude/local"
    fi

    export PATH
}

orkestrator_shell_quote() {
    if [ -z "${1:-}" ]; then
        printf "''"
        return 0
    fi

    printf "%s" "$1" | sed "s/'/'\\\\''/g; 1s/^/'/; \$s/\$/'/"
}

orkestrator_write_export() {
    name="$1"
    value="$2"
    file="$3"

    printf "export %s=" "$name" >> "$file"
    orkestrator_shell_quote "$value" >> "$file"
    printf "\n" >> "$file"
}

orkestrator_get_runtime_var() {
    case "$1" in
        PATH) printf "%s" "${PATH:-}" ;;
        BUN_INSTALL) printf "%s" "${BUN_INSTALL:-}" ;;
        CARGO_HOME) printf "%s" "${CARGO_HOME:-}" ;;
        GOPATH) printf "%s" "${GOPATH:-}" ;;
        PNPM_HOME) printf "%s" "${PNPM_HOME:-}" ;;
        DENO_INSTALL) printf "%s" "${DENO_INSTALL:-}" ;;
        PYENV_ROOT) printf "%s" "${PYENV_ROOT:-}" ;;
        RYE_HOME) printf "%s" "${RYE_HOME:-}" ;;
        UV_TOOL_BIN_DIR) printf "%s" "${UV_TOOL_BIN_DIR:-}" ;;
        VOLTA_HOME) printf "%s" "${VOLTA_HOME:-}" ;;
        NVM_DIR) printf "%s" "${NVM_DIR:-}" ;;
        FNM_DIR) printf "%s" "${FNM_DIR:-}" ;;
        *) return 1 ;;
    esac
}

orkestrator_capture_runtime_env() {
    mkdir -p "$(dirname "$ORKESTRATOR_RUNTIME_ENV_FILE")"
    orkestrator_add_common_runtime_paths

    tmp_file="${ORKESTRATOR_RUNTIME_ENV_FILE}.$$"
    {
        printf "# Generated by Orkestrator. Do not edit.\n"
        printf "# Contains only whitelisted runtime path variables.\n"
    } > "$tmp_file"

    for name in PATH BUN_INSTALL CARGO_HOME GOPATH PNPM_HOME DENO_INSTALL PYENV_ROOT RYE_HOME UV_TOOL_BIN_DIR VOLTA_HOME NVM_DIR FNM_DIR; do
        value="$(orkestrator_get_runtime_var "$name")"
        if [ -n "$value" ]; then
            orkestrator_write_export "$name" "$value" "$tmp_file"
        fi
    done

    chmod 600 "$tmp_file"
    mv "$tmp_file" "$ORKESTRATOR_RUNTIME_ENV_FILE"
}

orkestrator_source_runtime_env() {
    if [ -f "$ORKESTRATOR_RUNTIME_ENV_FILE" ]; then
        # shellcheck source=/dev/null
        . "$ORKESTRATOR_RUNTIME_ENV_FILE"
    fi

    orkestrator_add_common_runtime_paths
}
