import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertCircle, CheckCircle2, Loader2, RefreshCw, Square } from "lucide-react";
import type { MultiReviewReviewerTranscript } from "@orkestrator/protocol/multi-review";
import type { MultiReviewTabData } from "@/types/paneLayout";
import { Button } from "@/components/ui/button";
import { MessageRenderBoundary } from "@/components/chat/MessageRenderBoundary";
import { NativeMessage } from "@/components/chat/NativeMessage";
import { VirtualizedMessageList } from "@/components/chat/VirtualizedMessageList";
import { getNativeMessageSearchText } from "@/components/chat/native-message-search";
import { StructuredReviewReportView } from "@/components/review/StructuredReviewReportView";
import { useEnvironmentStore } from "@/stores/environmentStore";
import { useVirtuosoScrollState } from "@/hooks";
import { findPreviousNativeMessage } from "@/lib/chat/native-message-adapters";
import { multiReviewReviewerScrollKey } from "@/lib/multi-review-keys";
import { showOnlyFinalStructuredReviewMessage } from "@/lib/structured-review-messages";
import * as backend from "@/lib/backend";
import { toPipelineTranscript } from "@/components/build-pipeline/pipeline-transcript";

/**
 * Each poll re-reads the reviewer's whole provider transcript, which in gateway
 * mode crosses a network. A review runs for minutes, so trade a little latency
 * on this read-only progress view for a materially cheaper steady state; the
 * backend caps the response and a status change refreshes immediately.
 */
export const REFRESH_INTERVAL_MS = 4_000;

const AGENT_LABELS = {
  claude: "Claude",
  codex: "Codex",
  cursor: "Cursor",
  grok: "Grok",
  opencode: "OpenCode",
} as const;

/**
 * The backend answers a deleted workflow or reviewer in band with these
 * messages. They are terminal for this read-only view: a transient error keeps
 * the poll running so the tab can recover, but a gone workflow would poll
 * forever.
 */
function isGoneError(reason: unknown): boolean {
  const message = reason instanceof Error ? reason.message : String(reason);
  return message.includes("Multi review workflow not found")
    || message.includes("Multi review reviewer not found");
}

interface MultiReviewReviewerTabProps {
  data: MultiReviewTabData & { reviewerId: string };
  isActive: boolean;
  loadTranscript?: typeof backend.getMultiReviewReviewerTranscript;
  stopReviewer?: typeof backend.stopMultiReviewReviewer;
}

export function toMultiReviewReviewerMessages(snapshot: MultiReviewReviewerTranscript) {
  const transcript = toPipelineTranscript(
    snapshot.messages,
    snapshot.agent,
    snapshot.startedAt ?? "1970-01-01T00:00:00.000Z",
  );
  // This backend-owned session has no interactive composer. Initial and schema-
  // correction requests are generated by the workflow, so keep the viewer on
  // reviewer outputs/tool calls instead of rendering pages of prompt or schema.
  const output = transcript.filter((message) => message.role !== "user");
  // The workflow's validated report is authoritative. Schema-shaped text in
  // the provider transcript is progress data and must never be shown as raw
  // JSON (or mistaken for an accepted result).
  return showOnlyFinalStructuredReviewMessage(output, false);
}

export function MultiReviewReviewerTab({
  data,
  isActive,
  loadTranscript = backend.getMultiReviewReviewerTranscript,
  stopReviewer = backend.stopMultiReviewReviewer,
}: MultiReviewReviewerTabProps) {
  const [snapshot, setSnapshot] = useState<MultiReviewReviewerTranscript | null>(null);
  const [transcriptError, setTranscriptError] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [stopping, setStopping] = useState(false);
  const requestGeneration = useRef(0);
  const inFlightGeneration = useRef<number | null>(null);
  const containerId = useEnvironmentStore(
    (state) => state.getEnvironmentById(data.environmentId)?.containerId,
  ) ?? undefined;

  const refresh = useCallback(async () => {
    const generation = requestGeneration.current;
    if (inFlightGeneration.current === generation) return;
    inFlightGeneration.current = generation;
    try {
      const next = await loadTranscript(data.workflowId, data.reviewerId);
      if (requestGeneration.current !== generation) return;
      setSnapshot(next);
      setTranscriptError(null);
    } catch (reason) {
      if (requestGeneration.current !== generation) return;
      setTranscriptError(reason instanceof Error ? reason.message : String(reason));
    } finally {
      if (inFlightGeneration.current === generation) inFlightGeneration.current = null;
    }
  }, [data.reviewerId, data.workflowId, loadTranscript]);

  /**
   * The workflow, not this tab, owns the reviewer's lifecycle. Stopping only
   * asks the backend to retire it; the transcript view then re-reads the
   * authoritative snapshot rather than assuming the new status locally.
   */
  const stop = useCallback(async () => {
    setStopping(true);
    setActionError(null);
    try {
      await stopReviewer(data.workflowId, data.reviewerId);
      // A poll may have captured `running` before the backend committed the stop
      // and still be awaiting provider messages. Fence that response out, then
      // force a new authoritative read instead of letting the in-flight guard
      // turn this refresh into a no-op.
      requestGeneration.current += 1;
      inFlightGeneration.current = null;
      await refresh();
    } catch (reason) {
      // Transcript polling continues after a refused action, but a successful
      // read must not erase the action failure before the user can read it.
      setActionError(reason instanceof Error ? reason.message : String(reason));
    } finally {
      setStopping(false);
    }
  }, [data.reviewerId, data.workflowId, refresh, stopReviewer]);

  useEffect(() => {
    setSnapshot(null);
    setTranscriptError(null);
    setActionError(null);
    setStopping(false);
    requestGeneration.current += 1;
  }, [data.reviewerId, data.workflowId]);

  useEffect(() => {
    if (!isActive) return;
    void refresh();
    const gone = transcriptError !== null && isGoneError(transcriptError);
    if (gone || (snapshot && snapshot.status !== "running" && snapshot.status !== "pending")) return;
    const interval = window.setInterval(() => void refresh(), REFRESH_INTERVAL_MS);
    return () => {
      window.clearInterval(interval);
      requestGeneration.current += 1;
    };
  }, [isActive, refresh, snapshot?.status, transcriptError]);

  const messages = useMemo(() => {
    if (!snapshot) return [];
    return toMultiReviewReviewerMessages(snapshot);
  }, [snapshot]);

  const scrollKey = multiReviewReviewerScrollKey(data.workflowId, data.reviewerId);
  const { virtuosoRef, scrollProps } = useVirtuosoScrollState({
    isActive,
    persistKey: scrollKey,
    environmentId: data.environmentId,
    stickToBottomOnActivation: true,
  });

  const running = snapshot?.status === "running";
  // A refused action stays visible until the user acts again, so an ordinary
  // transcript failure must not displace it. A gone workflow or reviewer is the
  // exception: it makes the action failure moot and is terminal for this view,
  // so reporting the stale action error instead would hide why polling stopped.
  const error = transcriptError !== null && isGoneError(transcriptError)
    ? transcriptError
    : actionError ?? transcriptError;
  const label = snapshot ? AGENT_LABELS[snapshot.agent] : "Reviewer";
  const stoppable = snapshot?.status === "running" || snapshot?.status === "pending";
  const statusLine = snapshot
    ? snapshot.status === "cancelled"
      ? "Stopped · excluded from the consolidated report"
      : snapshot.stalledSince && running
        ? "No activity for a while · stop it to continue without this reviewer"
        : `${snapshot.model}${snapshot.reasoningEffort ? ` · ${snapshot.reasoningEffort}` : ""} · Read only`
    : "Loading read-only transcript…";

  return (
    <div className="flex h-full min-h-0 flex-col bg-background">
      <header className="flex shrink-0 items-center justify-between gap-3 border-b border-border/60 px-4 py-3 sm:px-5">
        <div className="min-w-0">
          <h1 className="truncate text-sm font-semibold">{label} review</h1>
          <p
            className={`truncate text-xs ${snapshot?.stalledSince && running ? "text-amber-500" : "text-muted-foreground"}`}
          >
            {statusLine}
          </p>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          {running ? <Loader2 className="size-4 animate-spin text-cyan-400" />
            : snapshot?.status === "completed" ? <CheckCircle2 className="size-4 text-emerald-500" />
              : snapshot?.status === "failed" ? <AlertCircle className="size-4 text-destructive" />
                : null}
          {stoppable && (
            <Button
              variant="outline"
              size="sm"
              disabled={stopping}
              aria-label="Stop this reviewer"
              title="Stop this reviewer; the Multi Review continues without it"
              onClick={() => void stop()}
            >
              {stopping
                ? <Loader2 className="mr-2 size-3.5 animate-spin" />
                : <Square className="mr-2 size-3.5" />}
              Stop
            </Button>
          )}
          <Button
            variant="ghost"
            size="icon"
            className="size-8"
            aria-label="Refresh reviewer transcript"
            onClick={() => void refresh()}
          >
            <RefreshCw className="size-3.5" />
          </Button>
        </div>
      </header>

      <div
        className="@container flex min-h-0 flex-1 flex-col"
        data-testid="multi-review-reviewer-transcript-body"
      >
        <VirtualizedMessageList
          messages={messages}
          computeItemKey={(_index, message) => message.id}
          resolvePreviousMessage={findPreviousNativeMessage}
          renderMessage={(_index, message, previous) => (
            // This read-only view re-reads the whole provider transcript every
            // few seconds while the reviewer streams, so a frame can hold a
            // message shape no renderer has seen before. One such message must
            // degrade to its own row — not hand the entire tab to the view
            // error boundary — and retries on the next poll's fresh snapshot.
            <MessageRenderBoundary resetKey={message}>
              <NativeMessage
                message={message}
                previousMessage={previous}
                assistantLabel={label}
                containerId={containerId}
                agentExpansionScope={data.environmentId}
                platform={snapshot?.agent}
              />
            </MessageRenderBoundary>
          )}
          emptyState={
            <div className="px-6 py-12 text-center text-sm text-muted-foreground">
              {error
                ? error
                : running
                  ? "The review is running. Its authoritative transcript will appear here as it is synchronized."
                  : snapshot
                    ? "No text transcript was produced for this review."
                    : "Loading reviewer transcript…"}
            </div>
          }
          footer={snapshot?.report ? (
            <div className="px-3 py-3 @sm:px-6">
              <StructuredReviewReportView
                className="mx-auto max-w-3xl"
                report={snapshot.report}
                heading="Reviewer report"
                collapsibleSections
                showRawJson={false}
              />
            </div>
          ) : error && messages.length > 0 ? (
            <div className="mx-3 mb-3 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive @sm:mx-6">
              {error}
            </div>
          ) : undefined}
          scrollProps={scrollProps}
          virtuosoRef={virtuosoRef}
          find={{
            isActive,
            getSearchText: getNativeMessageSearchText,
          }}
        />
      </div>
    </div>
  );
}
